name: dotnet package

on:
  push:
    branches:
      - master

env:
  bepinexdl: https://github.com/BepInEx/BepInEx/releases/download/v5.4.21/BepInEx_unix_5.4.21.0.zip


jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: [ '7.0.x' ]

    steps:
      - uses: actions/checkout@v3
      - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: ${{ matrix.dotnet-version }}

      - name: Install NuGet
        uses: nuget/setup-nuget@v1

      - name: Install dependencies
        run: dotnet restore

      - name: Delete old Valheim directory
        run: |
          rm -rdf /home/runner/.steam/steam/steamapps/common/Valheim

      - name: Download and install SteamCMD (64-bit)
        run: |
          mkdir steamcmd
          cd steamcmd
          wget https://steamcdn-a.akamaihd.net/client/installer/steamcmd_linux.tar.gz
          tar -xvzf steamcmd_linux.tar.gz
          cd ..

      - name: Install Valheim
        run: |
          ./steamcmd/steamcmd.sh +force_install_dir /home/runner/.steam/steam/steamapps/common/Valheim +login anonymous +app_update 896660 validate +exit

      - name: Install BepInEX
        run: |
          mv /home/runner/.steam/steam/steamapps/common/Valheim/valheim_server_Data/ /home/runner/.steam/steam/steamapps/common/Valheim/valheim_Data/
          wget -O "${{ env.bepinexdl }}"
          unzip bepinex.zip -d ~/BepInEx
          mv ~/BepInEx/BepInExPack_Valheim/* /home/runner/.steam/steam/steamapps/common/Valheim/

      - name: Build
        run: dotnet build --configuration Release --no-restore
